name: Deploy Robots

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker Image
      run: |
        docker build -t robots .
        docker save robots -o ./robots.tar
        chmod 644 ./robots.tar
        ls -la

    - name: Upload the Docker image to the server
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./robots.tar"
          target: "~/robots.tar"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
            # Stop the container if it exists
            docker stop robots || true

            # Remove the container if it exists
            docker rm robots || true

            # Remove the image if it exists
            docker rmi robots || true

            # Load the new Docker image from the tar file
            docker load -i ~/robots/robots.tar

            # Run the new Docker container in detached mode, mapping port 80 to the host
            docker run -d --name robots -p 8090:80 robots

            # Clean up by removing the tar file
            rm -rf ~/robots.tar